### ISSUE TITLE
Tips

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#1]
**User Story 1:**
As a visitor who is struggling with my mental health, I need access to some tips to help me manage my stress, so that I can feel better and more prepared.

**Acceptance Criteria:**

- [x] The site has a section using Bootstrap cards with tips on how to manage stress & anxiety.
- [x] The cards must be visually appealing.

**Tasks:** 

- [x] Utilise Bootstrap cards, and include a well-curated selection of tips for handling stress and anxiety.
- [x] Use calming imagery for each card.
- [x] Create a "message to myself" modal form.
