### ISSUE TITLE
Affirmations

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#17]
**User Story:**
As a regular user of the site, I'd like to visit from time to time to read positive affirmations to give my mental health a lift for the day.

**Acceptance Criteria:**
- [ ] The site has a positive affirmations section
- [ ] The affirmations are curated to be relevant and uplifting

**Tasks:**
- [ ] Create a positive affirmations section
- [ ] Curate a list of affirmations
- [ ] Provide each in a carousel with a suitable calming image in the background
