### ISSUE TITLE
Symptoms

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#3]
**User Story 2:**
As the parent/friend of someone who I am concerned may be struggling with their mental health, I would like information on how to recognise common symptoms so that I can better support them.

**Acceptance Criteria:**
- [x] Using the Bootstrap card structure again, the site will have a selection of different symptoms which may indicate a mental health condition.
- [x] Images should be more infographic in style and work as a visual aid.
- [x] The section should link to where to go in an emergency, as well as a comprehensive list of local mental health services/charities.

**Tasks:**
- [x] Use Bootstrap cards and infographics to display symptoms.
- [x] Ensure call to action is easy to see and non-triggering.
- [x] Curate a comprehensive list of local services/charities.
