### ISSUE TITLE
Emergency

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#4]
**User Story:**
As someone who is experiencing a mental health crisis, I need information on where I can go in an emergency so that I can be protected and helped.

**Acceptance Criteria:**
- [x] #18
- [x] There is a call to action button for anyone needing emergency help.
- [x] The links and information are presented in a supportive way so as not to worsen any feelings of anxiety.

**Tasks:**
- [x] Put a button front and centre to enable quick access to emergency care.
- [x] Provide links to a well curated list of emergency care givers.
- [x] Maintain the colour scheme so that, whilst the button and links stand out, they do not agitate or trigger.
