### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#5]
**User Story:**
As a general user, I need a site which is familiar to navigate, and is calming & well organised so that I can feel confident using it.

**Acceptance Criteria:**
- [x] The site has a calming appearance with a hero image including an encouraging message.
- [x] The site layout is familiar and conforms to current popular designs.
- [x] The site is laid out in a logical manner so that information is easy to find.
- [x] The site must be designed for the most frequently used devices, mobiles, first.  It must be responsive to look good on all devices.

**Tasks:**
- [x] Use a colour palette generator to select a colour scheme which is calming.
- [x] Use navigation bar with hamburger drop down (for mobiles), main body featuring cards and a footer which includes social media links.
- [x] Use normal layout and user-test that the flow is as expected.
- [x] Create the site using mobile-first techniques and ensure that it is responsive.
