### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#6]
**User Story:**
Remembering that mental health conditions can affect anyone, as a user who is visually impaired I need websites to be accessible for me so that I am not prevented from using them.

**Acceptance Criteria:**
- [x] #20
- [x] Every image used and every link has alt text or an aria-label.
- [x] Text should be laid out in a way which makes it easily readable.

**Tasks:**
- [x] Test colours used together via the WebAIM contract checker (https://webaim.org/resources/contrastchecker/).
- [x] Implement alt text and aria labels on every image and link.
- [x] Test site with a screen reader.
