### ISSUE TITLE
Learner

### ISSUE THREAD

**Issue by CharlesTack** [CharlesTack/mentalhealth#7]
**User Story:**
As someone interested in working in the mental health sector, I would like information on job/learning opportunities and details of events which I can attend, so that I can make the best first step on my career.

**Acceptance Criteria:**
- [ ] The site has a separate section for career information.
- [ ] The site provides links to recruitment and education services.
- [ ] There is an events section with a form for registering for updates.

**Tasks:**
- [ ] Create a separate section for career information.
- [ ] Curate and provide links for recruitment and information services.
- [ ] Create a form to allow users to register for events updates.
